def draw_hospital():
    print("    _______________    ")
    print("    |             |    ")
    print("    |    |   |    |    ")
    print("    |    |---|    |    ")
    print("    |    |   |    |    ")
    print("    |             |    ")
    print("    |             |    ")
    print(" ___|_____________|___ ")
    print(" |                   | ")
    print(" |                   | ")
    print(" |      _______      | ")
    print(" |      |  |  |      | ")
    print("_|______|__|__|______|_")
    return
